"""Added Password column to Users table

Revision ID: 7309e9caa2e1
Revises: 25e2c9110a6d
Create Date: 2026-08-24 13:09:17.484233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7309e9caa2e1'
down_revision: Union[str, Sequence[str], None] = '25e2c9110a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))

    op.execute(
        """
        UPDATE users
        SET password_hash = 'YOUR_GENERATED_HASH_HERE'
        WHERE password_hash IS NULL
        """
    )

    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.String(),
        nullable=False
    )    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
