"""Rename Documents column description to summary

Revision ID: 738c8b1f181f
Revises: dbae3ac837e0
Create Date: 2026-08-06 12:51:37.549316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738c8b1f181f'
down_revision: Union[str, Sequence[str], None] = 'dbae3ac837e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_column('documents', 'description', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_column('documents', 'summary', 'description')
    # ### end Alembic commands ###
