"""Add Description Column in Documents Table

Revision ID: dbae3ac837e0
Revises: f490a0fe2541
Create Date: 2026-08-06 11:07:46.154755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbae3ac837e0'
down_revision: Union[str, Sequence[str], None] = 'f490a0fe2541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
